### PR TITLE
Initial #![no_std] mode

### PR DESCRIPTION
**Pull request by est31**
Addresses most of #20 , except for the panic catching inside the linux module.

### CODE REVIEW

**Comment by est31** [comment]
libcore doesn't have functionality to catch panics. Also I'm not sure whether we'd be creating a circular dependency if we are calling this code inside the panic handler. Removing the catching is bad as well though because panicing through FFI boundaries *is* UB.

**Comment by philipc** [comment]
We could add an unsafe API where it is the caller's responsibility to ensure it doesn't panic.

**Comment by fitzgen** [comment]
It is really hard to verify code paths are panic-free (as I know you know ;) ).

Another option would be to internally do a full pass that copies the relevant info out, and then iterate over the copies with the user-supplied callback. This should make the code that needs to be panic-free easier to manage (certainly for users, since it is only the crate's responsibility now). It also doesn't sound very performant. Perhaps we could add some kind of query/filter API so we could only copy what is necessary and potentially break out of the loop early as well. Thoughts?

I need to mull this over a bit.

**Comment by philipc** [comment]
It's only a problem if it unwinds, right? So what I should have said is that it is the caller's responsibility to ensure it doesn't unwind. Maybe libstd's usage can be a bit special so that it can set an internal flag that forces any panics to abort instead of unwinding? So I'm hoping for a solution where we can still guarantee that it is correct (whereas it is hard to ensure any copying API we implement would never unwind).

**Comment by est31** [comment]
> Maybe libstd's usage can be a bit special so that it can set an internal flag that forces any panics to abort instead of unwinding?

Seems that [this is what is happening already](http://play.rust-lang.org/?gist=cb7b605ba9e4c04eefc1ee569dd25da7&version=stable&mode=debug). So I think we are fine with adding an unsafe variant of the API without any panic catching.

**Comment by est31** [comment]
The period of my contributions to Rust upstream [has reached an end](https://gist.github.com/est31/de7f851ec80576d5cf7bccac3962aed7). Thus I'm unable to continue my work on this. I still think something like this is a great addition. I urge anyone interested in this change to adopt and continue it from here on.

**Note:** This PR isn't technically to a Rust upstream repository but I'm still closing it as it was created as a part of me pushing the libbacktrace → addr2line migration over the finish line.

**Pull request closed without merging**
