### PR TITLE
on iOS with XCode set to debug mode, _dyld_get_image_vmaddr_slide will always return 0 (on some library)

### LINKED ISSUE #70: Panic on iOS
I tested `findshlibs` on iOS simulator with `cargo dinghy` and the following code:
```rust
#[cfg(test)]
mod tests {
    use findshlibs::{TargetSharedLibrary, SharedLibrary, Segment, TARGET_SUPPORTED};
    #[test]
    fn it_works() {
        println!("findshlibs TARGET_SUPPORTED={}", TARGET_SUPPORTED);
        TargetSharedLibrary::each(|shlib| {
            println!(
                "TargetSharedLibrary::each id={:?} name={:?} \
            image_addr={:?} image_size={:?} image_vmaddr={:?}",
                shlib.id(),
                shlib.name(),
                shlib.actual_load_addr(),
                shlib.len(),
                shlib.stated_load_addr(),
            );
    
            for seg in shlib.segments() {
                println!(
                    "TargetSharedLibrary::each::seg    {}: segment {}",
                    seg.actual_virtual_memory_address(shlib),
                    seg.name(),
                );
            }
        });
        panic!();
    }
}
```
And then I found it panicked in `TargetSharedLibrary::each`, with the following output:
```
➜  find git:(master) ✗ cargo dinghy -d IosSimDevice test
[2021-10-21T02:39:37Z INFO  cargo_dinghy] Targeting platform 'auto-ios-x86_64' and device 'B4986B21-02A1-4ABB-B017-CE35BEA46EFC'
[/Users/<>/.cargo/registry/src/github.com-1ecc6299db9ec823/dinghy-lib-0.4.62/src/ios/platform.rs:70] &self.toolchain = Toolchain {
    rustc_triple: "x86_64-apple-ios",
}
    Finished debug [unoptimized + debuginfo] target(s) in 0.02s

running 1 test
test tests::it_works ... FAILED

failures:

---- tests::it_works stdout ----
findshlibs TARGET_SUPPORTED=true
TargetSharedLibrary::each id=Some(Uuid("2a92fc99-72a9-38ed-8ddd-af4c25080124")) name="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/dyld_sim" image_addr=Avma(4455350272) image_size=368640 image_vmaddr=Svma(0)
TargetSharedLibrary::each::seg    0x1098f4000: segment __TEXT
TargetSharedLibrary::each::seg    0x10994e000: segment __DATA_CONST
TargetSharedLibrary::each::seg    0x109951000: segment __DATA
TargetSharedLibrary::each::seg    0x109985000: segment __LINKEDIT
TargetSharedLibrary::each id=Some(Uuid("1af405cd-ad77-3487-81fb-8637beaa5c55")) name="/Users/bytedance/Library/Developer/CoreSimulator/Devices/B4986B21-02A1-4ABB-B017-CE35BEA46EFC/data/Containers/Bundle/Application/AF1E2F25-F5C0-4314-9257-F4A218AAA354/Dinghy.app/Dinghy" image_addr=Avma(4454170624) image_size=638976 image_vmaddr=Svma(4294967296)
TargetSharedLibrary::each::seg    0x97d4000: segment __PAGEZERO
TargetSharedLibrary::each::seg    0x1097d4000: segment __TEXT
TargetSharedLibrary::each::seg    0x109870000: segment __DATA_CONST
TargetSharedLibrary::each::seg    0x10987c000: segment __DATA
TargetSharedLibrary::each::seg    0x109880000: segment __LINKEDIT
thread 'tests::it_works' panicked at 'If we have a header pointer, slide should be valid', /Users/<>/.cargo/registry/src/github.com-1ecc6299db9ec823/findshlibs-0.10.0/src/macos/mod.rs:289:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I'll try to fix them.

### PR DESCRIPTION
**Pull request by name1e5s**
Fix #70

### CODE REVIEW

**Comment by name1e5s** [comment]
> Going to release this to avoid panics for anyone using it, but still would be good to do some checks that this is all working satisfactorily. Thanks!

Sorry for the late response. I've checked result shows by the following code on XCode iOS Simulator:
```rust
    #[test]
    fn have_text_or_pagezero() {
        macos::SharedLibrary::each(|shlib| {
            println!("shlib = {:?}@{:x}", shlib.name(), shlib.virtual_memory_bias().0);

            let mut found_text_or_pagezero = false;
            for seg in shlib.segments() {
                println!("    segment = {:?}@{:x}", seg.name(), seg.stated_virtual_memory_address().0);

                found_text_or_pagezero |= seg.name() == "__TEXT";
                found_text_or_pagezero |= seg.name() == "__PAGEZERO";
            }
            assert!(found_text_or_pagezero);
        });
        panic!();
    }
```

And got the following result(partial):
```
---- macos::tests::have_text_or_pagezero stdout ----
shlib = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/dyld_sim"@10d0e7000
    segment = "__TEXT"@0
    segment = "__DATA_CONST"@5a000
    segment = "__DATA"@5d000
    segment = "__LINKEDIT"@91000
shlib = "/Users/bytedance/Library/Developer/CoreSimulator/Devices/B6AA6540-0074-425B-A321-2C1D1BF8FE11/data/Containers/Bundle/Application/D0DC00F9-DA34-43E7-83EF-23CDEF46574B/Dinghy.app/Dinghy"@cfe7000
    segment = "__PAGEZERO"@0
    segment = "__TEXT"@100000000
    segment = "__DATA_CONST"@100094000
    segment = "__DATA"@1000a0000
    segment = "__LINKEDIT"@1000a4000
shlib = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libiconv.2.dylib"@0
    segment = "__TEXT"@7fff53869000
    segment = "__DATA_CONST"@7fff89bf80a0
    segment = "__DATA"@7fff8323d550
    segment = "__LINKEDIT"@7fffc02ac000
shlib = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.B.dylib"@0
    segment = "__TEXT"@7fff537bf000
    segment = "__DATA_CONST"@7fff89bf0a68
    segment = "__DATA"@7fff83236bf8
    segment = "__LINKEDIT"@7fffc02ac000
```

It seems that Apple does a "pre-relocate" for their system library on debug mode, which makes the result useless. 
What will happens on real iOS device with release mode needs a further test. I'll test it once my XCode upgrades to the newest version to support my iPhone running iOS 15.

**Comment by philipc** [comment]
The [handling for this in backtrace-rs](https://github.com/rust-lang/backtrace-rs/blob/b02ed04a7e915659eea6fb1607df469b84a30638/src/symbolize/gimli/libs_macos.rs#L132) might give some clues.

**Comment by name1e5s** [comment]
> The [handling for this in backtrace-rs](https://github.com/rust-lang/backtrace-rs/blob/b02ed04a7e915659eea6fb1607df469b84a30638/src/symbolize/gimli/libs_macos.rs#L132) might give some clues.

According to apple's dyld source code [here](https://opensource.apple.com/source/dyld/dyld-852.2/dyld3/MachOLoaded.cpp.auto.html), the slide(or virtual_memory_bias) of a shared library is computed by subtracting first `__TEXT` segment's stated_virtual_memory_address  from address of `mach_header`, but it seems that in practice it doesn't return a correct result when dealing with [dyld_shared_cache](https://iphonedev.wiki/index.php/Dyld_shared_cache), we'd better calculate `virtual_memory_bias` by our self as [what lldb does](https://github.com/rust-lang/backtrace-rs/issues/318#issuecomment-626098698).

PS:
Result of code mentioned [here](https://github.com/gimli-rs/findshlibs/pull/71#issuecomment-958812540) on macOS 12 is wrong too.
```
shlib = "/Users/bytedance/Documents/Temp/ffi_findshlibs/target/debug/deps/ffi_findshlibs-f76e109e73d8401f"@e4b1000
    segment = "__PAGEZERO"@0
    segment = "__TEXT"@100000000
    segment = "__DATA_CONST"@10009c000
    segment = "__DATA"@1000a8000
    segment = "__LINKEDIT"@1000ac000
shlib = "/usr/lib/libiconv.2.dylib"@1629c000
    segment = "__TEXT"@7ff80b16c000
    segment = "__DATA_CONST"@7ff84082c520
    segment = "__DATA"@7ff8423bf880
    segment = "__LINKEDIT"@7ff8800a4000
shlib = "/usr/lib/libcharset.1.dylib"@1629c000
    segment = "__TEXT"@7ff80b0c2000
    segment = "__DATA_CONST"@7ff84082a600
    segment = "__DATA"@7ff8423b9f68
    segment = "__LINKEDIT"@7ff8800a4000
```

**Comment by name1e5s** [comment]
> The [handling for this in backtrace-rs](https://github.com/rust-lang/backtrace-rs/blob/b02ed04a7e915659eea6fb1607df469b84a30638/src/symbolize/gimli/libs_macos.rs#L132) might give some clues.

It seems that _dyld_get_image_vmaddr_slide returns 0 is caused by `lldb`, which disables ASLR.

**Comment by name1e5s** [comment]
> > The [handling for this in backtrace-rs](https://github.com/rust-lang/backtrace-rs/blob/b02ed04a7e915659eea6fb1607df469b84a30638/src/symbolize/gimli/libs_macos.rs#L132) might give some clues.
> 
> It seems that _dyld_get_image_vmaddr_slide returns 0 is caused by `lldb`, which disables ASLR.

For example, running the code mentioned [here](https://github.com/gimli-rs/findshlibs/pull/71#issuecomment-958812540) on macOS with lldb shows the a image with slide of 0:
```
➜  deps git:(master) ✗ lldb ffi_findshlibs-f76e109e73d8401f
(lldb) target create "ffi_findshlibs-f76e109e73d8401f"
Current executable set to '/Users/bytedance/Documents/Temp/ffi_findshlibs/target/debug/deps/ffi_findshlibs-f76e109e73d8401f' (x86_64).
(lldb) r
Process 26174 launched: '/Users/bytedance/Documents/Temp/ffi_findshlibs/target/debug/deps/ffi_findshlibs-f76e109e73d8401f' (x86_64)

running 1 test
test tests::it_works ... FAILED

failures:

---- tests::it_works stdout ----
shlib = "/Users/bytedance/Documents/Temp/ffi_findshlibs/target/debug/deps/ffi_findshlibs-f76e109e73d8401f"@0
    segment = "__PAGEZERO"@0
    segment = "__TEXT"@100000000
    segment = "__DATA_CONST"@10009c000
    segment = "__DATA"@1000a8000
    segment = "__LINKEDIT"@1000ac000
shlib = "/usr/lib/libiconv.2.dylib"@1629c000
    segment = "__TEXT"@7ff80b16c000
    segment = "__DATA_CONST"@7ff84082c520
    segment = "__DATA"@7ff8423bf880
    segment = "__LINKEDIT"@7ff8800a4000
shlib = "/usr/lib/libcharset.1.dylib"@1629c000
    segment = "__TEXT"@7ff80b0c2000
    segment = "__DATA_CONST"@7ff84082a600
    segment = "__DATA"@7ff8423b9f68
    segment = "__LINKEDIT"@7ff8800a4000
shlib = "/usr/lib/libSystem.B.dylib"@1629c000
    segment = "__TEXT"@7ff80b12e000
    segment = "__DATA"@7ff8423bd150
    segment = "__LINKEDIT"@7ff8800a4000
```

The result of the system library on macOS is similar to what list [here](https://github.com/gimli-rs/findshlibs/pull/71#issuecomment-958812540), and it result in useful values.

**Pull request merged**
